apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-app
  labels:
    app: file-upload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload-app
  template:
    metadata:
      labels:
        app: file-upload-app
    spec:
      containers:
        - name: file-upload-app
          image: rahees9983/file-upload-app:v2
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: dynatrace-sealed-secret
---
apiVersion: v1
kind: Service
metadata:
  name: file-upload-app-service
spec:
  type: LoadBalancer
  selector:
    app: file-upload-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
