# ============================================================
# Kustomization for ArgoCD Vault Plugin
# ============================================================
# Apply with: kubectl apply -k .
# ============================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - avp-secret.yaml
  - argocd-cm-plugin.yaml

patches:
  - path: argocd-repo-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
